"use strict";

const WARNING_CODES = {
  PARTIAL_ENRICHMENT: "PARTIAL_ENRICHMENT",
  SIFRADN_NOT_FOUND: "SIFRADN_NOT_FOUND",
  SIFRADN_NO_PARTS: "SIFRADN_NO_PARTS",
  PART_NAME_NOT_FOUND: "PART_NAME_NOT_FOUND"
};

module.exports = {
  WARNING_CODES
};
